### ISSUE TITLE
Add dark mode functionality  

### ISSUE THREAD

**Issue by Abhijay007** [CircuitVerse/Blog#56]
Add dark mode functionality on the blog website

**Comment by astelrastogi** [comment]
I want to work on this issue

**Comment by yashikajotwani12** [comment]
I want to work on this issue

**Comment by ShreyaPrasad1209** [comment]
@yashikajotwani12 go ahead 👍🏻

**Comment by astelrastogi** [comment]
this is the link where i need to add the functionality right?
 https://blog.circuitverse.org/

**Comment by AsherThomasBabu** [comment]
@ShreyaPrasad1209 I assume that the special event is done and the issue is available to other contributors?

I've written code in the theme/northendlab-hugo/layouts/partials folder locally, that adds the dark mode functionality. Upon trying to push the changes, I noticed that I cannot create a pull request for changes to the repo at CircuitVerse. Rather have to create a PR to the original repo at hugo-themes. Since this is a change that is specific to this project, I did not think doing this was right.

I'd be happy to receive input on how this issue can be solved.

**Comment by gouravmohanty7070** [comment]
Hey! Can I work on it?

**Comment by tachyons** [comment]
Sorry, No.  There is already a PR fir this

**Comment by AsherThomasBabu** [comment]
@tachyons, as suggested, I did open an issue on the templates' repository regarding adding a dark mode toggle, but did not receive any input there. What do you suggest we do for this now?
